// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ0LlNTo7dw7Pz6fXWrACR5_QumM6Vrfk',
    appId: '1:1033449353833:web:ae81346e5589cc5c0fa8f8',
    messagingSenderId: '1033449353833',
    projectId: 'quotes-project-201b3',
    authDomain: 'quotes-project-201b3.firebaseapp.com',
    storageBucket: 'quotes-project-201b3.firebasestorage.app',
    measurementId: 'G-Z8GQPTS5VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjSAKDNWrLDYZ8p2N3GaYywcaNS2rTd6w',
    appId: '1:1033449353833:android:44f4313888aed14e0fa8f8',
    messagingSenderId: '1033449353833',
    projectId: 'quotes-project-201b3',
    storageBucket: 'quotes-project-201b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTR1HjeRLPpeuOP0CJxhirck1my_vKRwo',
    appId: '1:1033449353833:ios:320dda0897f6ca4a0fa8f8',
    messagingSenderId: '1033449353833',
    projectId: 'quotes-project-201b3',
    storageBucket: 'quotes-project-201b3.firebasestorage.app',
    iosClientId: '1033449353833-7j4c8p3e5g5s3vmjbq9rfbgi32drqimi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterQuotes',
  );
}
